development:
  secret_key_base: d107bbe818bff1ec4ff202d281a359d0bcdbc6f5e11a5358dc313616e4c6fbc29cfd1571eef8e0b08fbc3e6225c2687bfee7ce064deb64769cb6600848d78f6e
  aws_access_key_id: AKIAIPFWZGJEFL4RDWBQ
  aws_secret_access_key: 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

test:
  secret_key_base: 3df9d3baf2ecf8e3dfb7ab2fc4ee6efebbb35569a5a714f06b293e8ad4442900301f2e71a1886fb0a508c0cf08a2eff1b8c3facb02642e15ff6248ce8b0d28a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: AKIAIPFWZGJEFL4RDWBQ
  aws_secret_access_key: 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
